[package]
authors = ["Rahix <rahix@rahix.de>"]
edition = "2018"
name = "noambition"
version = "0.1.0"

[dependencies]
glium = "0.32.1"
image = "0.24.5"
log = "0.4.17"
nalgebra = "0.32.1"
rand = "0.8.5"

[dependencies.vis-core]
optional = false
path = "../vis-core"
