[audio]
window = "nuttall"
conversions = 300
rate = 8000
read_size = 256
recorder = "cpal"

[midi]
# If you want to select a specific port:
#
# output_port = "Midi Through:Midi Through Port-0 14:0"

[noa]
fps = 40

[noa.cols]
rows = 50
num = 30
depth = 30.0
mid_dist = 0.1
speed = 0.1
slowdown = 0.95
speed_deviation = 50.0
width = 10.0
note_width = 6
colors = [
    [1.000000, 0.007443, 0.318893, 1.0],
    [0.915586, 0.704283, 0.214133, 1.0],
    [0.044844, 0.646290, 0.590788, 1.0],
    [0.130165, 0.022207, 0.276140, 1.0],
    [1.000000, 0.007443, 0.318893, 1.0],
    [0.915586, 0.704283, 0.214133, 1.0],
    [0.044844, 0.646290, 0.590788, 1.0],
    [0.130165, 0.022207, 0.276140, 1.0],
    [1.000000, 0.007443, 0.318893, 1.0],
    [0.915586, 0.704283, 0.214133, 1.0],
    [0.044844, 0.646290, 0.590788, 1.0],
    [0.130165, 0.022207, 0.276140, 1.0],
]

amp_top = 0.7
amp_bottom = 0.2

[noa.camera]
height = 1.0
look_height = 0.8
