[package]
authors = ["Rahix <rahix@rahix.de>"]
edition = "2021"
name = "no-dmx"
version = "0.1.0"

[dependencies]
log = "0.4.6"
midir = "0.9.1"
nalgebra = "0.16.9"
rand = "0.6.0-pre.1"

[dependencies.vis-core]
optional = false
path = "../vis-core"
